services:
  - type: web
    name: job-matching-platform-analysis
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    branch: main
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
